package main

import (
	"flag"
	"fmt"
	"os"

	tea "github.com/charmbracelet/bubbletea"
)

const (
	defaultProfileFilename = "coverage.out"
)

func main() {
	var profileFilename string

	flag.StringVar(
		&profileFilename, "profile", defaultProfileFilename,
		"File name of coverage profile generated by go test -coverprofile coverage.out",
	)
	flag.Parse()

	m := model{
		activeView:      activeViewList,
		profileFilename: profileFilename,
	}

	if err := tea.NewProgram(m, tea.WithAltScreen()).Start(); err != nil {
		fmt.Println("Error running program:", err)
		os.Exit(1)
	}
}
