name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install go-task
        uses: arduino/setup-task@v1
      - name: Run tests
        run: task test
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.out

